sylius_grid:
    grids:
        owl_admin_equipment_attribute:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.equipment_attribute.class%"
            sorting:
                position: asc
            fields:
                code:
                    type: string
                    label: owl.ui.code
                    sortable: ~
                name:
                    type: string
                    label: owl.ui.name
                position:
                    type: string
                    enabled: false
                    sortable: ~
                type:
                    type: twig
                    label: owl.ui.type
                    sortable: ~
                    options:
                        template: "@OwlUi/Grid/Field/label.html.twig"
            filters:
                code:
                    type: string
                    label: owl.ui.code
            actions:
                main:
                    create:
                        type: create_product_attribute
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
