sylius_grid:
    grids:
        owl_admin_locale:
            driver:
                name: doctrine/orm
                options:
                    class: "%owl.model.locale.class%"
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: owl.ui.code
                    sortable: ~
                name:
                    type: twig
                    label: owl.ui.name
                    path: .
                    sortable: code
                    options:
                        template: "@OwlAdmin/Locale/Grid/Field/name.html.twig"
            filters:
                code:
                    type: string
                    label: owl.ui.code
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
