owl_admin_ajax_admin_user_permission_assign:
    path: /assign
    methods: [POST]
    defaults:
        _controller: owl.controller.admin_user_permission:assignAction
        _format: json
        _sylius:
            serialization_groups: [ADD]
            form: Owl\Bundle\RbacBundle\Form\Type\AssignType
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        id: $id
                form:
                  ajax: true
                permission:
                    group: user
                    description: owl.ui.permission.assign_permission_to_user

owl_admin_ajax_admin_user_permission_revoke:
    path: /revoke
    methods: [DELETE]
    defaults:
        _controller: owl.controller.admin_user_permission:revokeAction
        _format: json
        _sylius:
            serialization_groups: [DELETE]
            form: Owl\Bundle\RbacBundle\Form\Type\AssignType
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        id: $id
                form:
                  ajax: true
                permission:
                    group: user
                    description: owl.ui.permission.revoke_permission_to_user