imports:
    - { resource: "@OwlUiBundle/Resources/config/app/config.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/app/owl/owl_mailer.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/rbac_role.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/admin_user.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/locale.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/suggestion.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/company.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/equipment.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/equipment_category.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/notification.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/equipment_attribute.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/equipment_event.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/equipment_refueling.yml" }
    # COMPANY ROLE
    - { resource: "@OwlAdminBundle/Resources/config/grids/company/equipment.yml" }
    - { resource: "@OwlAdminBundle/Resources/config/grids/company/admin_user.yml" }
    # USER ROLE
    - { resource: "@OwlAdminBundle/Resources/config/grids/user/equipment.yml" }

parameters:
    env(SYLIUS_ADMIN_ROUTING_PATH_NAME): ""
    owl_admin.path_name: '%env(resolve:SYLIUS_ADMIN_ROUTING_PATH_NAME)%'
    sylius.security.admin_regex: "^/%owl_admin.path_name%"

tinymce:
    selector: '.tinymce'

owl_user:
    permission_provider:
        admin: 'rbac'

sylius_grid:
    templates:
        action:
            update_admin_user: "@OwlAdmin/AdminUser/Grid/Action/update.html.twig"
            assign_permissions_admin_user: "@OwlAdmin/AdminUser/Grid/Action/assign_permissions.html.twig"
            registration_admin_user: "@OwlAdmin/AdminUser/Grid/Action/registration.html.twig"
            create_product_attribute: "@OwlAdmin/EquipmentAttribute/Grid/Action/create.html.twig"
            equipment_menu: "@OwlAdmin/Equipment/Grid/Action/menu.html.twig"
        filter:
            entities: '@OwlUi/Grid/Filter/entities.html.twig'
            location: '@OwlUi/Grid/Filter/location.html.twig'

owl_ui:
    events:
        sylius.admin.index:
            blocks:
                header:
                    template: "@OwlAdmin/Crud/Index/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Index/_content.html.twig"
                    priority: 10

        sylius.admin.create:
            blocks:
                header:
                    template: "@OwlAdmin/Crud/Create/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Create/_content.html.twig"
                    priority: 10

        sylius.admin.ajax.create:
            blocks:
                header:
                    template: "@OwlAdmin/Crud/Ajax/Create/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Ajax/Create/_content.html.twig"
                    priority: 10

        sylius.admin.update:
            blocks:
                header:
                    template: "@OwlAdmin/Crud/Update/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Update/_content.html.twig"
                    priority: 10

        sylius.admin.ajax.update:
            blocks:
                header:
                    template: "@OwlAdmin/Crud/Ajax/Update/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Ajax/Update/_content.html.twig"
                    priority: 10

        sylius.admin.layout.sidebar:
            blocks:
                logo:
                    template: "@OwlAdmin/Layout/_logo.html.twig"
                    priority: 20
                menu:
                    template: "@OwlAdmin/Layout/_menu.html.twig"
                    priority: 10

        sylius.admin.layout.javascripts:
            blocks:
                scripts:
                    template: "@OwlAdmin/Layout/_scripts.html.twig"
                    priority: 10

        sylius.admin.layout.stylesheets:
            blocks:
                styles:
                    template: "@OwlAdmin/Layout/_styles.html.twig"
                    priority: 10

        sylius.admin.login.before_form:
            blocks:
                flashes:
                    template: "@OwlAdmin/Security/_flashes.html.twig"
                    priority: 10

        # TINYMCE
        owl.admin.tinymce:
            blocks:
                tinymce:
                    template: "@OwlAdmin/_tinymce.html.twig"

        sylius.admin.layout.topbar_left:
            blocks:
                sidebar_toggle:
                    template: "@OwlAdmin/Layout/_sidebarToggle.html.twig"
                    priority: 300

        sylius.admin.layout.topbar_right:
            blocks:
                add_suggestion:
                    template: "@OwlAdmin/Layout/_add_suggestion.html.twig"
                    priority: 50
                notifications:
                    template: "@OwlAdmin/Layout/_notificationWidget.html.twig"
                    priority: 30
                security:
                    template: "@OwlAdmin/Layout/_security.html.twig"
                    priority: 10

        sylius.admin.login.content:
            blocks:
                tree:
                    template: "@OwlAdmin/Security/_content.html.twig"
                    priority: 10

        owl.admin.dashboard.content:
            blocks:
                header:
                    template: "@OwlAdmin/Dashboard/_header.html.twig"
                    priority: 40
                statistics:
                    template: "@OwlAdmin/Dashboard/_description.html.twig"
                    priority: 30

        #SERVICE
        owl.admin.service.index.header:
            blocks:
                content:
                    template: "@OwlAdmin/Service/Index/Header/_content.html.twig"
                    priority: 20
                breadcrumb:
                    template: "@OwlAdmin/Service/Index/Header/_breadcrumb.html.twig"
                    priority: 10

        owl.admin.service.index.content:
            blocks:
                header:
                    template: "@OwlAdmin/Service/Index/_headerWidget.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Service/Index/_content.html.twig"
                    priority: 10

        owl.admin.service.index.content.main:
            blocks:
                content:
                    template: "@OwlAdmin/Service/Index/Content/_grid.html.twig"
                    priority: 10

        owl.admin.service.show.content:
            blocks:
                header:
                    template: "@OwlAdmin/Service/Show/_headerWidget.html.twig"
                    priority: 40
                breadcrumb:
                    template: "@OwlAdmin/Service/Show/_breadcrumb.html.twig"
                    priority: 30
                content:
                    template: "@OwlAdmin/Service/Show/_contentWidget.html.twig"
                    priority: 10

        owl.admin.service.show.header.content:
            blocks:
                content:
                    template: "@OwlAdmin/Service/Show/_header.html.twig"
                    priority: 20
                menu:
                    template: "@OwlAdmin/Service/Show/_headerMenu.html.twig"
                    priority: 10

        owl.admin.service.show.information:
            blocks:
                primary:
                    template: "@OwlAdmin/Customer/Show/Details/_primary.html.twig"
                    priority: 30
                email:
                    template: "@OwlAdmin/Customer/Show/Details/_email.html.twig"
                    priority: 20
                contact:
                    template: "@OwlAdmin/Customer/Show/Details/_contact.html.twig"
                    priority: 10

        #Equipment
        owl.admin.equipment.show.content:
            blocks:
                header:
                    template: "@OwlAdmin/Equipment/Show/_headerWidget.html.twig"
                    priority: 40
                breadcrumb:
                    template: "@OwlAdmin/Equipment/Show/_breadcrumb.html.twig"
                    priority: 30
                content:
                    template: "@OwlAdmin/Equipment/Show/_contentWidget.html.twig"
                    priority: 10

        owl.admin.equipment.show.tab_details:
            blocks:
                content:
                    template: "@OwlAdmin/Equipment/Show/Tab/_details.html.twig"
                    priority: 20
        owl.admin.equipment.show.tab_history_equipment:
            blocks:
                content:
                    template: "@OwlAdmin/Equipment/Show/Tab/_history_equipment.html.twig"
                    priority: 20

        owl.admin.equipment.show.tab_event_equipment:
            blocks:
                content:
                    template: "@OwlAdmin/Equipment/Show/Tab/_events.html.twig"
                    priority: 20

        owl.admin.equipment.show.tab_refueling_equipment:
            blocks:
                content:
                    template: "@OwlAdmin/Equipment/Show/Tab/_refuelings.html.twig"
                    priority: 20

        owl.admin.equipment.ajax.show.header.content:
            blocks:
                content:
                    template: "@OwlAdmin/Equipment/Show/_header.html.twig"
                    priority: 20

        owl.admin.notification.ajax.details.content:
            blocks:
                header:
                    template: "@OwlAdmin/Notification/Details/_headerWidget.html.twig"
                    priority: 40
                content:
                    template: "@OwlAdmin/Notification/Details/_contentWidget.html.twig"
                    priority: 10

        owl.admin.notification.ajax.details.header.content:
            blocks:
                content:
                    template: "@OwlAdmin/Notification/Details/_header.html.twig"
                    priority: 20

        owl.admin.registration.ajax.show.content:
            blocks:
                header:
                    template: "@OwlAdmin/AdminUser/Registration/_headerWidget.html.twig"
                    priority: 40
                content:
                    template: "@OwlAdmin/AdminUser/Registration/_contentWidget.html.twig"
                    priority: 10

        owl.admin.registration.ajax.show.header.content:
            blocks:
                content:
                    template: "@OwlAdmin/AdminUser/Registration/_header.html.twig"
                    priority: 20

        # RBAC
        # Permission
        owl.admin.rbac_permission.index.header:
            blocks:
                content:
                    template: "@OwlAdmin/Rbac/Permission/Availables/Header/_content.html.twig"
                    priority: 20
                breadcrumb:
                    template: "@OwlAdmin/Rbac/Permission/Availables/Header/_breadcrumb.html.twig"
                    priority: 10

        owl.admin.rbac_permission.index.content:
            blocks:
                header:
                    template: "@OwlAdmin/Rbac/Permission/Availables/_headerWidget.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Rbac/Permission/Availables/_content.html.twig"
                    priority: 10

        # Role availables
        owl.admin.rbac_role_availables.index.header:
            blocks:
                content:
                    template: "@OwlAdmin/Rbac/Role/Availables/Header/_content.html.twig"
                    priority: 20
                breadcrumb:
                    template: "@OwlAdmin/Rbac/Role/Availables/Header/_breadcrumb.html.twig"
                    priority: 10

        owl.admin.rbac_role_availables.index.content:
            blocks:
                header:
                    template: "@OwlAdmin/Rbac/Role/Availables/_headerWidget.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Rbac/Role/Availables/_content.html.twig"
                    priority: 10

        # User prmission
        owl.admin.user_permission.index.header:
            blocks:
                content:
                    template: "@OwlAdmin/User/Permission/Header/_content.html.twig"
                    priority: 20
                breadcrumb:
                    template: "@OwlAdmin/User/Permission/Header/_breadcrumb.html.twig"
                    priority: 10

        owl.admin.user_permission.index.content:
            blocks:
                header:
                    template: "@OwlAdmin/User/Permission/_headerWidget.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/User/Permission/_content.html.twig"
                    priority: 10

        owl.admin.category.index.header:
            blocks:
                content:
                    template: "@OwlAdmin/Category/Index/Header/_content.html.twig"
                    priority: 20
                breadcrumb:
                    template: "@OwlAdmin/Category/Index/Header/_breadcrumb.html.twig"
                    priority: 10

        owl.admin.category.index.content:
            blocks:
                header:
                    template: "@OwlAdmin/Category/Index/_headerWidget.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Crud/Index/_content.html.twig"
                    priority: 10

        owl.admin.system_setting:
            blocks:
                header:
                    template: "@OwlAdmin/Setting/System/Index/_header.html.twig"
                    priority: 20
                content:
                    template: "@OwlAdmin/Setting/System/Index/_content.html.twig"
                    priority: 10

        #COMPANY
        owl.admin.company.show.content:
            blocks:
                header:
                    template: "@OwlAdmin/Company/Show/_headerWidget.html.twig"
                    priority: 40
                breadcrumb:
                    template: "@OwlAdmin/Company/Show/_breadcrumb.html.twig"
                    priority: 30
                content:
                    template: "@OwlAdmin/Company/Show/_contentWidget.html.twig"
                    priority: 10
        owl.admin.company.show.header.content:
            blocks:
                content:
                    template: "@OwlAdmin/Company/Show/_header.html.twig"
                    priority: 20
                menu:
                    template: "@OwlAdmin/Company/Show/_headerMenu.html.twig"
                    priority: 10
        owl.admin.company.show.tab_details:
            blocks:
                content:
                    template: "@OwlAdmin/Company/Show/Tab/_details.html.twig"
                    priority: 20
        owl.admin.company.show.tab_equipment:
            blocks:
                content:
                    template: "@OwlAdmin/Company/Show/Tab/_equipment.html.twig"
                    priority: 20
        owl.admin.company.show.tab_user:
            blocks:
                content:
                    template: "@OwlAdmin/Company/Show/Tab/_user.html.twig"
                    priority: 20
