owl_admin_suggestion_file:
    resource: |
        alias: owl.suggestion_file
        section: admin
        path: /
        templates: "@OwlAdmin\\Crud"
        only: ['show', 'delete']
        permission: true
        vars:
            delete:
                redirect:
                    header: xhr
                form:
                    ajax: true
                permission:
                    group: suggestion
                    description: owl.ui.permission.delete_file
    type: sylius.resource

owl_admin_suggestion_file_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: owl.controller.suggestion_file::createAction
        _format: json
        _sylius:
            section: admin
            serialization_groups: [Uploaded]
            permission: true
            form: Owl\Bundle\CoreBundle\Form\Type\Suggestion\SuggestionUploadFileType
            factory:
                method: createForSubjectWithUploader
                arguments:
                    - "expr:notFoundOnNull(service('owl.repository.suggestion').findOneById($suggestionId))"
                    - "expr:service('owl.context.admin_user').getUser()"
            vars:
                permission:
                    group: suggestion
                    description: owl.ui.permission.create_file

owl_admin_suggestion_file_update:
    path: /{id}/update
    methods: [GET,PUT]
    defaults:
        _controller: owl.controller.suggestion_file::updateAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/Crud/Ajax/update.html.twig"
            factory:
                method: createForSubjectWithUploader
                arguments:
                    - "expr:notFoundOnNull(service('owl.repository.suggestion').findOneById($suggestionId))"
                    - "expr:service('owl.context.admin_user').getUser()"
            vars:
                redirect:
                    save:
                        route: owl_admin_service_update
                        parameters: 
                            id: $suggestionId
                        hash: files
                form:
                    ajax: true
                    actions: 
                        - { name: "save", icon: "plus", color: "blue"}
                serialization_groups: [AjaxShow]
                route:
                    parameters:
                        suggestionId: $suggestionId
                        id: $id
                permission:
                    group: suggestion
                    description: owl.ui.permission.update_file
