owl_admin_suggestion_file_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: owl.controller.suggestion_file::createAction
        _format: json
        _sylius:
            section: admin
            serialization_groups: [Uploaded]
            permission: true
            form: Owl\Bundle\CoreBundle\Form\Type\Suggestion\SuggestionUploadFileType
            factory:
                method: createForSubjectWithUploader
                arguments:
                    - suggestion
                    - "expr:service('owl.context.admin_user').getUser()"
            parents:
                - 
                    resource: owl.suggestion
                    repository: 
                        method: find
                        arguments: 
                            id: $suggestionId
            vars:
                permission:
                    group: suggestion
                    description: owl.ui.permission.create_file

owl_admin_suggestion_file_update:
    path: /{id}/update
    methods: [GET,PUT]
    defaults:
        _controller: owl.controller.suggestion_file::updateAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/Crud/Ajax/update.html.twig"
            parents:
                - 
                    resource: owl.suggestion
                    repository: 
                        method: find
                        arguments: 
                            id: $suggestionId
            vars:
                redirect:
                    save:
                        route: owl_admin_service_update
                        parameters: 
                            id: $suggestionId
                        hash: files
                form:
                    ajax: true
                    actions: 
                        - { name: "save", icon: "plus", color: "blue"}
                serialization_groups: [AjaxShow]
                route:
                    parameters:
                        id: $id
                        fileId: $fileId
                permission:
                    group: suggestion
                    description: owl.ui.permission.update_file

owl_admin_suggestion_file_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: owl.controller.suggestion_file::deleteAction
        _sylius:
            section: admin
            redirect: 
                header: xhr
            permission: true
            parents:
                - 
                    resource: owl.suggestion
                    repository: 
                        method: find
                        arguments: 
                            id: $suggestionId
            vars:
                redirect:
                    header: xhr
                form:
                    ajax: true
                permission:
                    group: suggestion
                    description: owl.ui.permission.delete_file
