owl_admin_suggestion_status_history_status:
    path: /history
    methods: [GET]
    defaults:
        _controller: owl.controller.suggestion_status:indexAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/Status/history.html.twig"
            repository:
                method: createHistoryListQueryBuilder
                arguments:
                    - "expr:isGranted(notFoundOnNull(service('owl.repository.suggestion').findOneById($suggestionId)))"
            vars:
                subheader: owl.ui.manage_suggestions
                icon: list
                referer: true
                permission:
                    group: suggestion
                    description: owl.ui.permission.history_status_suggestion

owl_admin_suggestion_status_change_status:
    path: /change-status
    methods: [GET,POST]
    defaults:
        _controller: owl.controller.suggestion_status::createAction
        _sylius:
            section: admin
            permission: true
            template: "@OwlAdmin/Crud/Ajax/create.html.twig"
            factory:
                method: createForSubjectWithOwner
                arguments:
                    - "expr:isGranted(notFoundOnNull(service('owl.repository.suggestion').findOneById($suggestionId)))"
                    - "expr:service('owl.context.admin_user').getUser()"
            vars:
                header: owl.ui.change_status_suggestion
                route:
                    name: owl_admin_suggestion_status_change_status
                    parameters: 
                        suggestionId: $suggestionId
                form:
                    ajax: true
                    actions: 
                        - { name: "referer", text: "owl.form.actions.save", icon: "plus", color: "blue"}
                serialization_groups: [AjaxShow]
                # templates:
                #     form: "@OwlAdmin/Suggestion/_form.html.twig"
                permission:
                    group: suggestion
                    description: owl.ui.permission.change_status_suggestion