owl_admin_ajax_equipment:
    resource: "@OwlAdminBundle/Resources/config/routing/ajax/equipment.yml"
    prefix: /equipments

owl_admin_ajax_rbac_permission:
    resource: "@OwlAdminBundle/Resources/config/routing/ajax/rbac_permission.yml"
    prefix: /rbac/permission

owl_admin_ajax_rbac_role:
    resource: "@OwlAdminBundle/Resources/config/routing/ajax/rbac_role.yml"
    prefix: /rbac/role/{id}

owl_admin_ajax_user_permission:
    resource: "@OwlAdminBundle/Resources/config/routing/ajax/user_permission.yml"
    prefix: /user/{id}/permission

owl_admin_ajax_equipment_attribute:
    resource: "@OwlAdminBundle/Resources/config/routing/ajax/equipment_attribute.yml"
    prefix: /equipment-attributes
