owl_admin_login:
    path: /
    methods: [GET]
    defaults:
        _controller: owl_core.controller.security::loginAction
        _sylius:
            template: "@OwlAdmin/Security/login.html.twig"
            logged_in_route: owl_admin_dashboard

owl_admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: owl_core.controller.security::checkAction

owl_admin_logout:
    path: /logout
    methods: [GET]

owl_admin_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: owl.controller.admin_user::createAction
        _sylius:
            template: "@OwlAdmin/Account/register.html.twig"
            form: Owl\Bundle\CoreBundle\Form\Type\User\AdminUserRegistrationType
            event: register
            redirect: 
                route: owl_admin_login
                parameters: []
                xhr: true
            flash: owl.admin_user.register
            vars:
                form:
                    ajax: true

owl_admin_user_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: owl.controller.admin_user::verifyAction
        _sylius:
            redirect: owl_admin_dashboard

owl_admin_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: owl.controller.admin_user::requestPasswordResetTokenAction
        _sylius:
            template: "@OwlAdmin/Account/requestPasswordReset.html.twig"
            redirect: 
                route: owl_admin_login
                parameters: []
                xhr: true
            vars:
                form:
                    ajax: true

owl_admin_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: owl.controller.admin_user::resetPasswordAction
        _sylius:
            template: "@OwlAdmin/Account/resetPassword.html.twig"
            redirect: 
                route: owl_admin_login
                parameters: []
                xhr: true
            vars:
                form:
                    ajax: true
